### ISSUE TITLE
how to compile?

### ISSUE THREAD

**Issue by leyed0** [uyjulian/pfsshell#1]
what is the process for compiling the code?

**Comment by uyjulian** [comment]
change directory to the code then type "make"

**Comment by leyed0** [comment]
thanks for the answer. I wasnt expecting this to be soon.
I am thinking about making a windows GUI for pfs that doesnt corrupts the HD like pfsexplorer... Make it look like an explorer window or something... Could you help me with your lybrary?

**Comment by uyjulian** [comment]
Sure, just send me an e-mail at (my github username) at gmail dot com
