### ISSUE TITLE
Possible DLL For using in other projects

### ISSUE THREAD

**Issue by leyed0** [uyjulian/pfsshell#15]
I would like to know if is it possible for you to compile a dll version of the library so i could use it in pfs hdd manager?

**Comment by uyjulian** [comment]
Yes, it is possible…

**Comment by uyjulian** [comment]
Now added `libps2hdd.dll`… https://github.com/ps2homebrew/pfsshell/releases/download/v1.1.1/pfsshell-v1.1.1-win32.7z
