### ISSUE TITLE
Scripting support

### ISSUE THREAD

**Issue by szpieg-z-krainy-deszczowcow** [uyjulian/pfsshell#17]
Would be awesome to have possibility to have full scripting support which could be invoke from cmd/ps or bash (e.g "pfsshell batch testscript.txt). With all possible to use commands. I was thinking about creating PS2 Auto Installer like similar on Xbox Classic and I'm not sure how to bypass jumping into another shell layer after reading disk; and this would be the easiest way for end user. Please consider to add such functionality.

**Comment by uyjulian** [comment]
You can already run scripts by piping commands into pfsshell (example `cat commands.txt | /path/to/pfsshell`).

**Comment by szpieg-z-krainy-deszczowcow** [comment]
Oh, didn't know that. Thanks.

**Comment by bignaux** [comment]
@szpieg-z-krainy-deszczowcow if you look, i start to write some scripting support in tcl https://github.com/bignaux/pfsshell/blob/mkpart/tests/pfsshell.tcl . It's very basic as a start, but tcl a great advantage to have expect feature that works fine with interactive software like pfsshell. I still need help, from test to search .

**Comment by GrindLogic** [comment]
@szpieg-z-krainy-deszczowcow 

I've kinda came up with a work around in [AutoIT](https://www.autoitscript.com/site/).
https://pastebin.com/P7EDEChB

Which could serve as a loader of sorts with some editing given an AutoIT compiled script can accept files or strings with some prep work. If so in the Help CHM that comes with AutoIT look under "Using AutoIT \ Command Line Parameters".

Other wise hopefully my code will work as a concept for you to develop around...lord knows more real programming langs can do a lot more than what AutoIT can.

**Comment by bignaux** [comment]
AutoIT, windows only, abandonned, non opensource. I see no interest when tcl example is already available https://github.com/ps2homebrew/pfsshell/blob/master/test/pfsshell_test.tcl . I should update it soon i hope.

**Comment by GrindLogic** [comment]
@bignaux 

hmm works under WINE on Linux, not abandoned but mature so updates are few and far between. The code I posted was certainly OSS...as for the run times...use to be but some folks couldn't honor the GPL2 lic...and worse still some folks charged others for the software. So it went closed source on v3.

I wish you the best on your code; I simply was posting something that would work....sorta.
