### ISSUE TITLE
Can't complete copy on Windows 10 with 500Gb SATA HDD

### ISSUE THREAD

**Issue by JihemB** [uyjulian/pfsshell#19]
Hello.

I use pfsshell on Windows 10 with a 500Gb SATA HDD formated PS2 (which actually works fine with OPL to launch ISO files).
I'm however unable to copy a simple .VCD (PS1 disc image) to the __.POPS directory ;-(
The behavious is the following : 
 - I run the "put" command.
 - The HDD light turns from green to orange for about 2 seconds
 - The HDD light turns back to green (showing write operations are over)
 - pfsshell stays stuck on the "put" command.

If I cancel the operation (Ctrl+C) I go back to Windows cmd. 
If I run again pfsshell I don't see the file copied in the target directory.

Here is a copy of the issues commands: 

> device \\.\PHYSICALDRIVE7
hdd: PS2 APA Driver v2.5 (c) 2003 Vector
hdd: max open = 1, 3 buffers
hdd: 17:54:11 11/21/2020
hdd: disk0: 0x3a384c40 sectors, max 0x01000000
hdd: checking log...
hdd: drive status 0, format version 00000002
hdd: version 0000 driver start.
pfs Playstation Filesystem Driver v2.2
ps2fs: (c) 2003 Sjeep, Vector and Florin Sasu
pfs Max mount: 1, Max open: 1, Number of buffers: 10
pfs version 0000 driver start.
# mount __.POPS
__.POPS:/# ls
drwxrwxrwx        512 2020-11-21 16:26 .
drwxrwxrwx        512 2020-11-21 16:26 ..
__.POPS:/# put diablo.VCD
^C

**Comment by uyjulian** [comment]
Try using a small file to test.
If that doesn't work, try a different interface on your computer.

If this is still an issue, re-open

**Comment by JihemB** [comment]
Hi.
Thanks for the tip. It works !
Actually the files I wanted to copy were bigger than the actual partition size ;-(
Shame there wasn't just an error message (out of room space) to state that.
Thanks.
