### ISSUE TITLE
Error mounting partition

### ISSUE THREAD

**Issue by israpps** [uyjulian/pfsshell#20]
the commands entered:
 device \\.\PHYSICALDRIVE1
 mkpart __common 128
 mount __common

*program output:*
pfs: Error: Invalid magic/version
(!) hdd0:__common: Input/output error.
(!) Exit code is -5.

windows 10 64 bit
hdd (320gb) conected with USB adapter
pfsshell 1.1.1 downloaded from this repository (executed as administrator of course)

**Comment by Darkshadow2** [comment]
After `mkpart` you need to do `mkfs` on the partition to initialize it.

**Comment by israpps** [comment]
it fixed the problems for partitions made on the program
but it also happens in partitions created in ulaunchelf 4.43a 41e4ebe

**Comment by uyjulian** [comment]
You need to format the partition before you can use them. If you just create the partition, it will not be formatted.
