### ISSUE TITLE
Can't copy entire folder or all files from folder to PS2 HDD's mounted partition

### ISSUE THREAD

**Issue by Mark-B97** [uyjulian/pfsshell#25]
I tried but couldn't find a way to "put" an entire folder full of files(such as OPL's ART folder) to the connected device.

I would expect to use * like in normal linux terminal stuff but:

```
+OPL:/ART# put *.jpg
*.jpg: Invalid argument
(!) Exit code is -1; errno 22 (Unknown error).
```

Also:

```
+OPL:/# put ART
ART: No such file or directory
(!) Exit code is -1; errno 2 (Unknown error).
+OPL:/# put "C:\Users\[USER]\Documents\OPL Manager\hdl_hdd\ART"
C:\Users\[USER]\Documents\OPL Manager\hdl_hdd\ART: Permission denied
(!) Exit code is -1; errno 13 (Unknown error).
```

**Comment by uyjulian** [comment]
The builtin shell `put` command only supports file inodes and not any other type of inode.

In the future, I plan to add FUSE support so you can use any tool you want to copy files as you want.
