### ISSUE TITLE
[ISSUE] NTFS to PFS

### ISSUE THREAD

**Issue by GDX-X** [uyjulian/pfsshell#28]
Hello, I discovered a strange bug with pfsshell If you have a new hard drive in NTFS or FAT32 format To put it in PS2 format You must format your drive once then unplug it and plug it back in then format it again so that it is correctly in PS2 format

On the other hand, if your hard drive is already in PS2 format, a single formatting will be sufficient.

**Comment by uyjulian** [comment]
This is a Windows issue with caching the partition table and not with pfsshell.  
Unplugging and replugging the storage device will unmap the partition table on all OS.

`kpartx -d /path/to/block/device` will unmap the partition on Linux.
