### ISSUE TITLE
[ISSUE]: HDD Not recognized

### ISSUE THREAD

**Issue by JustuhN00B** [uyjulian/pfsshell#35]
### Checks

- [X] I have checked existing issues for duplicates and found none

### Describe the issue

When I try to Navigate PFSshell.exe to my Playstation 2 Internal HDD I keep getting and error that states: 
hdd2: No such file or directory.

I have verified that it IS a working PS2 HDD when I use the WinHiip application and run games from OPL on the machine.

![Preview](https://user-images.githubusercontent.com/98182163/150580109-4c8e77ef-4f8b-4353-bae7-49b364d9dc74.PNG)

### Console model

SCPH-39001

**Comment by AKuHAK** [comment]
@JustuhN00B first, check the last [beta release](https://github.com/ps2homebrew/pfsshell/releases/tag/latest)
second, try to use wmic path (https://github.com/ps2homebrew/pfsshell/blob/master/README.md#quickstart)

**Comment by AKuHAK** [comment]
Closed as no response from OP
