### ISSUE TITLE
[ISSUE]: PS2 Drive doesn't mount. PFS Shell crashes instead. 

### ISSUE THREAD

**Issue by Elliander** [uyjulian/pfsshell#42]
### Checks

- [X] I have checked existing issues for duplicates and found none

### Describe the issue

I attached my 2 TB PS2 hard drive to my Windows 10 PC via a USB 3.0 enclosure. I then checked my computer's disk management to verify where the drive was located. It showed up as:

```
DIsk11
Unknown
1863.02 GB
Not Initialized

1863.02 GB Unallocated
```

I then ran PFS Shell as administrator and typed in:

`device hdd11:`

and then PFS Shell promptly closed itself. I then opened a command prompt with administrator, changed directory, and ran from there. This is what I got:

![pfsshell](https://user-images.githubusercontent.com/15022396/179496356-dcbaf063-841f-4f31-a304-99758a388360.jpg)

I crashed after finding "Invalid Argument" so I figured that maybe I shouldn't have typed the : symbol so I tried typing 

`device hdd11`

after opening the program again and then it says "No Such File or Directory" which is also the error I get when I try:

`device /dev/sdb `

Then, just to make sure there wasn't a problem with the drive, I put it back in the PS2 and it loaded up just fine. It boots directly to the drive with MCBoot, but I can't add POPSTARTER to it or add my games to it without access to it via a PC since the hdd connects via a Game Star Network Adapter, meaning no access via ethernet cable. 

### Console model

SCPH-50001/N

**Comment by AKuHAK** [comment]
@Elliander pfsshell syntax for Windows was changed a long time ago. Take a look into [the readme](https://github.com/ps2homebrew/pfsshell#quickstart) about UNC paths.

P.S. On a side note, not related to the current problem. Can you provide a [PS2Ident dump](https://github.com/ps2homebrew/PS2Ident/releases/tag/latest) of your SCPH-50001/N ? It will help in the [MechaPwn](https://github.com/MechaResearch/MechaPwn/blob/LangPwn/README.md) investigation.

**Comment by Elliander** [comment]
I see. I thought UNC was an option rather than a requirement. When I enter the following command in windows PowerShell:

`wmic diskdrive get Caption,DeviceID,InterfaceType`

I get:

`ST2000DM 001-1ER164 SCSI Disk Device  \\.\PHYSICALDRIVE11  SCSI`

Where,

Caption: ST2000DM 001-1ER164 SCSI Disk Device
DeviceID: \\.\PHYSICALDRIVE11 
Interface: SCSI

Since I see the following under DeviceID:

`\\.\PHYSICALDRIVE11`

and given that the readme says to use:

`device /path/to/device`

I guess I should be using:

`device \\.\PHYSICALDRIVE11`

?

As far as PS2Ident goes, if I understand correctly, that needs to run from the PS2 itself, right? Wouldn't I need to gain access to the internal hdd before doing so? I'd be more than happy to help in any way I can once I get access to the drive figured out. 

**EDIT:** Using 

`device \\.\PHYSICALDRIVE11`

Seems to be what I needed. When I use that I get:

```
> device \\.\PHYSICALDRIVE11
hdd: PS2 APA Driver v2.5 (c) 2003 Vector
hdd: max open = 1, 3 buffers
hdd: 19:26:33 07/18/2022
hdd: disk0: 0xe8e074c0 sectors, max 0x04000000
hdd: checking log...
hdd: drive status 0, format version 00000002
hdd: version 0000 driver start.
pfs Playstation Filesystem Driver v2.2
ps2fs: (c) 2003 Sjeep, Vector and Florin Sasu
pfs Max mount: 1, Max open: 1, Number of buffers: 10
pfs version 0000 driver start.
#
```

So now, assuming that nothing else is significantly different from guides, I can install POPSTARTER to play my games.
