### ISSUE TITLE
[REQUEST] Add WinHiip-like features

### ISSUE THREAD

**Issue by ParzivalWolfram** [uyjulian/pfsshell#6]
There's no Linux alternative to WinHiip and WinHiip doesn't get drive access from Wine. Can you add the ability to add images to the drive?

**Comment by uyjulian** [comment]
What do you mean by "images"? You can already add disk images for POPS, and you can use hdl_dump to add HDL games to the HDD.

**Comment by ParzivalWolfram** [comment]
doesn't hdl_dump require the PS2 to act as a server? My PS2 doesn't like my
network and uLE hangs on boot for me, but those are just my issues...
anyways, "images" as in ISOs/BINs. What is "POPS"?

**Comment by uyjulian** [comment]
No, you can just hook up HDD block device to hdl_dump

**Comment by ParzivalWolfram** [comment]
Oh.


go ahead and close this then.
