### ISSUE TITLE
mount command "No such device." error code -19

### ISSUE THREAD

**Issue by madmodder123** [uyjulian/pfsshell#7]
This issue occurs with both the original pfsshell application (0.2 on windows) and the most up to date compiled version on linux (Ubuntu 18 LTS).

So I have been trying to salvage my OPL config files off my HDD (I believe my MBR is corrupt, LaunchElf and HDD Checker 0.964 report that the drive is not formatted).
After correctly selecting my device I attempt to mount the +OPL partition using "mount +OPL" (I have tried a lot of different variations of it incase my syntax was wrong). I receive the following error:

```
(!) hdd0:+OPL: No such device.
(!) Exit code is -19.
```
It seems like it is trying to use the first HDD even though I had already selected the correct drive ("device /dev/sdb" on linux, "device hdd2:" on windows)

Here is the output when I select the device:
```
> device /dev/sdb
hdd: PS2 APA Driver v2.5 (c) 2003 Vector
hdd: max open = 1, 3 buffers
hdd: 20:40:48 04/25/2019
hdd: disk0: 0xe8e088af sectors, max 0x04000000
hdd: checking log...
hdd: drive status 1, format version 00000000
hdd: version 0000 driver start.
pfs Playstation Filesystem Driver v2.2
ps2fs: (c) 2003 Sjeep, Vector and Florin Sasu
pfs Max mount: 1, Max open: 1, Number of buffers: 10
pfs version 0000 driver start.
```
I know the partitions are there, I can list all of them using hdl salvage.

Anyone have any ideas or am I just screwed?

**Comment by uyjulian** [comment]
Use `ls` after `device` to check if the partition is listed.

**Comment by madmodder123** [comment]
Same error when I try that.
```
dopen: "hdd0:" failed with -19
(!) lspart: No such device.
(!) Exit code is -19.
```

I even tried booting my PC with a linux live DVD with ONLY the PS2 HDD connected incase it was somehow always pointing to hdd0, but that still produced the same results.

**Comment by uyjulian** [comment]
That means that the HDD is detected as not formated.

**Comment by uyjulian** [comment]
In that situation, WinHiip may be able to help you if the HDD is detected as not formatted.

**Comment by madmodder123** [comment]
@uyjulian 
Unfortunately my drive is over 1TB so I can't use WinHIIP :/

**Comment by uyjulian** [comment]
Try using this tool. https://www.psx-place.com/threads/hddchecker.3855/

Unfortunately, I am out of advice.
