### ISSUE TITLE
Drive File Descriptor : Invalid argument.

### ISSUE THREAD

**Issue by zentasumu** [uyjulian/pfsshell#8]
First off, I've checked the file descriptor and it return nonzero.

Seems that read() and write() needs buffer sizes/count of 512 like so for it to succeed else it returns an invalid argument error.

Also lseek() allows seeking to non block sized offsets but it makes read() and write() return with invalid argument.

Removing lseek continued pfsshell on my chosen hard drive. Then I executed an initialize command afterwards. It was partially successful, as it only made the __mbr partition.

![image](https://user-images.githubusercontent.com/16412733/58381901-d04e0580-7ff5-11e9-85c6-350b9cb6113b.png)

Hope this sheds some light on the situation.

Removing lseek makes the hdd_length zero so that explains the no space left error.

**Comment by uyjulian** [comment]
Thanks for the information. I may take a look into it at a later date.

**Comment by Darkshadow2** [comment]
Hmm, that's a lot like the bug that kept it from getting the correct device size on macOS. I wonder if the `ioctl` code would work there?

**Comment by zentasumu** [comment]
Updated the post.

Using lseek, read and write only needs sizes/offset of 512, no alignment needed, sorry about that.

**Comment by zentasumu** [comment]
Also from how it looks like we really do have to use platform specific API when it comes to getting the hard drive info at least.

lseek works now but it doesn't return zero when it goes past the size of the drive, and just continues. I am not sure why its doing that.

**Comment by techyzen101** [comment]
Alright, so here's what I've gathered:

- HDDs only allow reading and writing per sector.

- On POSIX oriented systems, the functions lseek, read, write, etc. have some sort of underlying algorithm that does all those sector reading and computing offset that make it seem like editing data from an offset non-multiple of a hdd block size is possible.

- On Windows, its a literal raw call, that is why it only works if the offset/size is a multiple hard disk block size.

**Comment by zentasumu** [comment]
Checked against the old pfsshell v0.2a.
We were having an integer overflow all this time.

Made a pull request fixing this for Windows, while keeping it POSIX ;)

[Link to pull request](../pull/10)
